### ISSUE TITLE
updating of irregular bits when correcting a layer

### ISSUE THREAD

**Issue by laurent-daniel-utt** [laurent-daniel-utt/MeshIneBits#103]
## Expected behaviour

When correcting a bit in order to make it regular number of irregular bits should be updated

But it is not

to reproduce simply correct a bit on a layer to make it regular

**Comment by laurent-daniel-utt** [comment]
step to overcome : go one layer up and don and get back

**Comment by perfectstrong** [comment]
It seems this is an uncaptured event.
