### ISSUE TITLE
MeshIneBits freezing by modifying the bits after save

### ISSUE THREAD

**Issue by durringn** [laurent-daniel-utt/MeshIneBits#105]
## Expected behaviour

It should be possible to modify the bits shape and position at any time and each layer.

## Actual behaviour

After saving the mesh, it is impossible to modify anything. MeshIneBits is freezing, we need to relaunch the software.

## Steps to reproduce the error

By opening a saved mesh and trying to modify something on the bits (shape/position)

## Steps to overcome:

Do not save the file. Try to do a "one shot" work on the piece, and save it at the end.

**Comment by laurent-daniel-utt** [comment]
well done
