### ISSUE TITLE
Display and information screen update bug

### ISSUE THREAD

**Issue by durringn** [laurent-daniel-utt/MeshIneBits#107]
## Expected behaviour

The display is updating automatically when changes are made on a layer in manual add bit mode

## Actual behaviour

The display of the modified bits does not update automatically after changes.
Same for the information in the table on the right of the screen (such as the number of irregular bits).

## Steps to reproduce the error

Simply by modifying a layer and watch at the display.

## How to overcome the problem

To perform this update, you must go to the upper (or lower) layer and then return to the one concerned. Changing the layer will update the display.

**Comment by laurent-daniel-utt** [comment]
Apparently solved by latest Do Quang Bao release
