### ISSUE TITLE
Layer modifying bug

### ISSUE THREAD

**Issue by durringn** [laurent-daniel-utt/MeshIneBits#110]
## Expected behaviour

It should be possible to modify the work made on each layer at any time.

## Actual behaviour

Once X layer is filled and we move to the filling of the upper layer, it is impossible to modify the work carried out on this layer X if the need is. We need to rebuild the layer from the beginning.

## Steps to reproduce the error

Work on a layer. Move to the upper or lower layer then return to the initial layer.

**Comment by laurent-daniel-utt** [comment]
solved
