### ISSUE TITLE
"economic bric pattern" scheme bug

### ISSUE THREAD

**Issue by durringn** [laurent-daniel-utt/MeshIneBits#112]
## Expected behaviour

Using the "economic bric pattern" scheme, the given spaces between the bits should be respected.

## Actual behaviour

With the "economic bric pattern" mode, the chosen space between two bits is not always respected.

## Steps to reproduce the error

Pave some layers with "economic bric pattern". Some of them should show the error.

## How to overcome the error

These zones without space between Bits needs to be moved "manually".

**Comment by Rinkichi75** [comment]
One of the reasons of the issue has been resolve.
Now the only problem, come from the cut of the bit where the machine take the bit.
The issue can be close, because the problem stated above is for every pattern.

**Comment by laurent-daniel-utt** [comment]
still algo coul be mdified in order to take nto account behaviour of "algo that cut a part for gripper usage". This latest interfere with placement algo creating unwanted large spaces between bits
