### ISSUE TITLE
cleanning and correcting copyright "about" windows and find a proper way to modify copyright mention of each java file

### ISSUE THREAD

**Issue by laurent-daniel-utt** [laurent-daniel-utt/MeshIneBits#136]

**Comment by UTTprojetsEtienne** [comment]
About windows corrected (dates and accents "é")
New way to modify all copyrights with IntelliJ
--> See [https://www.jetbrains.com/help/idea/copyright.html](https://www.jetbrains.com/help/idea/copyright.html)
All copyrights have been updated !

@laurent-daniel-utt I will explain you soon !
