### ISSUE TITLE
IA documentation and explanation

### ISSUE THREAD

**Issue by laurent-daniel-utt** [laurent-daniel-utt/MeshIneBits#183]
For the IA t be trained correctly external surfaces should be populated turning clockwise and internal surfaces anticlockwise. This information should be mentionned when starting an IA recording, and also the fact that small side of bits should intersect with border to be efficent.

**Comment by UTTprojetsEtienne** [comment]
Done, with the method `UPPToolsIA.ShowDialogStartStoringBits()`

<img width="490" alt="image" src="https://user-images.githubusercontent.com/60063320/148553902-cf1a4079-716f-4039-b578-fb78f9fa5745.png">
